name: deploy-app
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    name: Push to test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: fastlane deployToAlpha
        env:
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
